import React, { useState, useRef } from 'react';
import { UploadCloud, FileArchive, CheckCircle2, AlertCircle, Loader2, ShieldCheck } from 'lucide-react';
import { api } from '../services/api';

export const UploadCenter: React.FC = () => {
  const [isDragging, setIsDragging] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [uploadState, setUploadState] = useState<'idle' | 'uploading' | 'validating' | 'success' | 'error'>('idle');
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState<{msg: string, type: 'info'|'success'|'error'}[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      setFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  const addLog = (msg: string, type: 'info'|'success'|'error' = 'info') => {
    setLogs(prev => [...prev, { msg, type }]);
  };

  const startUpload = async () => {
    if (!file) return;
    setUploadState('uploading');
    setLogs([]);
    setProgress(20);
    try {
      if (file.size > 5 * 1024 * 1024) throw new Error('Manifest exceeds the 5 MB API limit.');
      addLog('Reading manifest without executing embedded content...', 'info');
      const manifest = JSON.parse(await file.text());
      setProgress(55);
      setUploadState('validating');
      addLog('Validating lablineage.manifest.v1 schema on the backend...', 'info');
      const result = await api.importManifest(manifest) as { bundleId: string; nodes: number; edges: number; evidence: number };
      setProgress(100);
      setUploadState('success');
      addLog(`Imported ${result.nodes} nodes, ${result.edges} edges and ${result.evidence} evidence records from ${result.bundleId}.`, 'success');
    } catch (error) {
      setUploadState('error');
      addLog(error instanceof Error ? error.message : 'Manifest import failed.', 'error');
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col max-w-4xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-slate-800">Upload Center</h2>
        <p className="text-slate-600 mt-1">Import a validated lablineage.manifest.v1 JSON file generated by the Edge Collector.</p>
      </div>

      <div className="bg-white border border-slate-200 rounded-lg shadow-sm p-8">
        
        {uploadState === 'idle' && (
          <div 
            className={`border-2 border-dashed rounded-xl p-12 flex flex-col items-center justify-center transition-colors cursor-pointer ${isDragging ? 'border-blue-500 bg-blue-50' : 'border-slate-300 bg-slate-50 hover:bg-slate-100'}`}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
          >
            <input type="file" ref={fileInputRef} className="hidden" accept=".json" onChange={handleFileSelect} />
            <UploadCloud size={48} className={`mb-4 ${isDragging ? 'text-blue-500' : 'text-slate-400'}`} />
            <p className="text-lg font-medium text-slate-700 mb-1">
              {file ? file.name : 'Click or drag a LabLineage manifest.json here'}
            </p>
            <p className="text-sm text-slate-500">
              {file ? `${(file.size / (1024 * 1024)).toFixed(2)} MB` : 'Maximum file size: 5 MB'}
            </p>
          </div>
        )}

        {uploadState !== 'idle' && (
          <div className="space-y-6">
            <div className="flex items-center space-x-4 p-4 bg-slate-50 rounded-lg border border-slate-200">
              <FileArchive size={32} className="text-blue-500" />
              <div className="flex-1">
                <div className="flex justify-between mb-1">
                  <span className="font-medium text-slate-800">{file?.name || 'handoff-bundle.tar.zst'}</span>
                  <span className="text-sm text-slate-500">{progress}%</span>
                </div>
                <div className="w-full bg-slate-200 rounded-full h-2">
                  <div className={`h-2 rounded-full transition-all duration-300 ${uploadState === 'success' ? 'bg-green-500' : uploadState === 'error' ? 'bg-red-500' : 'bg-blue-600'}`} style={{ width: `${progress}%` }}></div>
                </div>
              </div>
            </div>

            <div className="bg-slate-900 rounded-lg p-4 font-mono text-sm h-64 overflow-y-auto space-y-2">
              {logs.map((log, idx) => (
                <div key={idx} className="flex items-start space-x-2 animate-in fade-in">
                  {log.type === 'info' && <Loader2 size={14} className="text-blue-400 animate-spin mt-0.5 flex-shrink-0" />}
                  {log.type === 'success' && <CheckCircle2 size={14} className="text-green-400 mt-0.5 flex-shrink-0" />}
                  {log.type === 'error' && <AlertCircle size={14} className="text-red-400 mt-0.5 flex-shrink-0" />}
                  <span className={log.type === 'error' ? 'text-red-400' : 'text-slate-300'}>{log.msg}</span>
                </div>
              ))}
              {uploadState === 'validating' && <div className="animate-pulse text-slate-500">_</div>}
            </div>
          </div>
        )}

        <div className="mt-8 flex justify-between items-center">
          <div className="flex items-center space-x-2 text-sm text-slate-500">
            <ShieldCheck size={16} />
            <span>The backend validates schema, bundle ID and Ed25519 signature policy before import.</span>
          </div>
          
          {uploadState === 'idle' && (
            <button 
              onClick={startUpload}
              disabled={!file}
              className="px-6 py-2 bg-blue-600 text-white rounded-md font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Upload & Validate
            </button>
          )}
          
          {(uploadState === 'success' || uploadState === 'error') && (
            <button 
              onClick={() => { setUploadState('idle'); setFile(null); setLogs([]); }}
              className="px-6 py-2 bg-slate-800 text-white rounded-md font-medium hover:bg-slate-700"
            >
              {uploadState === 'success' ? 'Upload Another' : 'Try Again'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
